server:
  port: 9999
spring:
  application:
    name: customer-test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 1 # 设置hystrix的超时时间为6000ms

